# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aftg_gompertz_makeham_mus <- function(a, b, c, s, x, mzb, lzb, hzb, steps) {
    .Call('_MortalityModels_aftg_gompertz_makeham_mus', PACKAGE = 'MortalityModels', a, b, c, s, x, mzb, lzb, hzb, steps)
}

gompertz_mu <- function(a, b, x) {
    .Call('_MortalityModels_gompertz_mu', PACKAGE = 'MortalityModels', a, b, x)
}

gompertz_s <- function(a, b, x) {
    .Call('_MortalityModels_gompertz_s', PACKAGE = 'MortalityModels', a, b, x)
}

gompertz_makeham_mu <- function(a, b, c, x) {
    .Call('_MortalityModels_gompertz_makeham_mu', PACKAGE = 'MortalityModels', a, b, c, x)
}

gompertz_makeham_s <- function(a, b, c, x) {
    .Call('_MortalityModels_gompertz_makeham_s', PACKAGE = 'MortalityModels', a, b, c, x)
}

phg_gompertz_mu <- function(a, b, s, x) {
    .Call('_MortalityModels_phg_gompertz_mu', PACKAGE = 'MortalityModels', a, b, s, x)
}

phg_gompertz_s <- function(a, b, s, x) {
    .Call('_MortalityModels_phg_gompertz_s', PACKAGE = 'MortalityModels', a, b, s, x)
}

phg_gompertz_makeham_mu <- function(a, b, c, s, x) {
    .Call('_MortalityModels_phg_gompertz_makeham_mu', PACKAGE = 'MortalityModels', a, b, c, s, x)
}

phg_gompertz_makeham_s <- function(a, b, c, s, x) {
    .Call('_MortalityModels_phg_gompertz_makeham_s', PACKAGE = 'MortalityModels', a, b, c, s, x)
}

